# -*- coding: utf-8 -*-
"""calculate_weekly_pay

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kg94Xcqvpm27zc2rRuz4edG_mbU_nXIv
"""

#program to calculate a person's weekly wage with and without overtime based on the user input

#first function get_input() is a value returning function and to get user inputs wage and hours worked
def get_input():
  wage = float(input("Enter your wage: "))
  hours = float(input("Enter your hours worked: "))
  return wage, hours

##second function weekly_pay() will display total earnings for the week based on teh wage and hours worked received
##from the first function. If hours is more than 40, calculate weekly pay with time-an-a-half for overtime
def weekly_pay(wage, hours):
  if hours <= 40:
    pay = wage * hours
    print(f"Your weekly pay is: ${pay}")
  else:
    pay = (wage * 40) + ((hours - 40) * (wage * 1.5))
    print(f"Your weekly pay with time-and-a-half for overtime is: ${pay}")

def main():
  wage, hours = get_input()
  weekly_pay(wage, hours)

main()