# -*- coding: utf-8 -*-
"""extract_first_name

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvuYglhGeJPV3_00w-oj-gQvZwQUkXNt
"""

#python modular program that extracts the first name from full name

## value returning function that extracts and returns the nfirst name from the full name. it will take the full name, split it into parts based on spaces
## using the split method, and returns the first part
def extract_first_name(full_name):
    name_parts = full_name.split()
    first_name = name_parts[0]
    return first_name

##extracting last name
def extract_last_name(full_name):
    name_parts = full_name.split()
    last_name = name_parts[1]
    return last_name

##main function gets the full name from user
def main():
    full_name = input("Enter your full name:")
    #first name is extracted using the extract_first_name()
    first_name = extract_first_name(full_name)
    print("Your first name is:", first_name)
    last_name = extract_last_name(full_name)
    print("Your last name is:", last_name)
#call main function
if __name__ == "__main__":
    main()