# -*- coding: utf-8 -*-
"""modular_program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lAGTtKILOSdr1HIT1z4Go9jQJKH6fZS
"""

#program to print a letter grade

#main calls the two functions
def main():
  #calls get_grade 3 times and stores each grade in 3 variables
  grade1 = get_grade()
  grade2 = get_grade()
  grade3 = get_grade()
  #uses value from get_grade to calculate percentage
  total = grade1 + grade2 + grade3
  #divide total by 300 since each grade was out of 100
  percentage_grade = (total/300)*100
  #print percentage and letter grade
  print(f"Your final grade percentage is{percentage_grade: .2f}%")
  #call letter_grade and pass percentage_grade as the argument to
  #determine the letter grade
  letter_grade(percentage_grade)

#get_grade
def get_grade():
  #get grade as input from user
  grade = float(input("Enter a grade between 0 and 100: "))
  #returns to calling function (main())
  return grade

#letter_grade takes percentage_grade as argument
def letter_grade(percentage_grade):
  #if elif else to determine letter grade based off the percentage
  if 100 >= percentage_grade >= 90:
    print("You passed with a grade A")
  elif 90 > percentage_grade >= 80:
    print("You passed with a grade B")
  elif 80 > percentage_grade >= 70:
    print("You passed with a grade C")
  elif 70 > percentage_grade >= 60:
    print("You passed with a grade D")
  else:
    print("You failed")

#call main
main()
#conditionally execute main
#if __name__ == "__main__":
  #main()