# -*- coding: utf-8 -*-
"""nested_loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oF-kieCkvsSEdPwALYUhGZGc7sSk2Ple
"""

#program that uses nested loops to collect data to calculate the total value

#get the range for the outer loop
outer_loop = int(input("Enter the range for the outside loop: ")) #controls how many times the outer loop will run
inside = 4 #fixed number of iterations for inner loop
total = 0 #initialize the total sum to zero
#if user enters 2 as the value for the outer loop, the program will run the outer loop 2 times, and each time the outer loop runs,
#the inner loop will run 4 times, asking the user for input each time
##outer loop
for i in range(outer_loop):
  print(f"\nOuter Loop Iteration {i + 1}")
  ##inner loop
  for j in range(inside):
    inner_loop = int(input(f"Enter value {j + 1} for inner loop: "))
    total += inner_loop #add user input to total

print(f"\nThe total value is {total}")