# -*- coding: utf-8 -*-
"""remove_empty_string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oobOMGidRG9eO-HWRTGDSuOjUM1H08zX
"""

#python function that removes empty strings from a list of strings
def remove_empty_strings(*string_lists): # *args syntax allows pass of multiple lists
    #create a new list to store the non-empty strings
    non_empty_list = []
    #iterate over the input list
    for string_list in string_lists:
        for string in string_list:
            #check if the string is not empty
            if string.strip():
                #add the non-empty string to the new list
                non_empty_list.append(string)
    return non_empty_list


def main():
    list1 = ["hello", "", "world", "", "python"]
    list2 = ["apple", "", "banana", "", "orange"]
    list3 = ["cat", "", "dog", "", "bird"]
    result = remove_empty_strings(list1, list2, list3)
    print(result)

if __name__ == "__main__":
    main()